spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mv
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  error:
    include-message: always
    include-stacktrace: on_param